-- stored procedure will be here
DELIMITER //

CREATE PROCEDURE CREATE_USER(IN ID INT,
  IN FIRST_NAME VARCHAR(16),
  IN LAST_NAME VARCHAR(16),
  IN MIDDLE_NAME VARCHAR(16),
  IN ROLE VARCHAR(16),
  IN CONTACT_ID INT,
  IN CITY VARCHAR(16),
  IN POST_CODE INT,
  IN STREET VARCHAR(16),
  IN HOUSE INT,
  IN FLAT INT,
  IN PHONE VARCHAR(16),
  IN EMAIL VARCHAR(16),
  IN LOGIN VARCHAR(16),
  IN PASSWORD VARCHAR(16))

  BEGIN

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
      ROLLBACK;
    END;

    DECLARE EXIT HANDLER FOR SQLWARNING
    BEGIN
      ROLLBACK;
    END;

    START TRANSACTION;
      insert into USERS(ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ROLE) values (ID, FIRST_NAME, LAST_NAME, MIDDLE_NAME, ROLE);
      insert into CONTACTS(ID, USER_ID, CITY, POST_CODE, STREET, HOUSE, FLAT, PHONE, EMAIL) values (CONTACT_ID, ID, CITY, POST_CODE, STREET, HOUSE, FLAT, PHONE, EMAIL);
      insert into CREDENTIALS(LOGIN, PASSWORD, USER_ID) values (LOGIN, PASSWORD, ID);

    COMMIT;
  END