CREATE DATABASE IF NOT EXISTS ADVERTISE_PRO;

USE ADVERTISE_PRO;

CREATE TABLE IF NOT EXISTS USERS
(
    ID VARCHAR(255) PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    MIDDLE_NAME VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONTACTS
(
    ID VARCHAR(255) PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL UNIQUE,
    CITY VARCHAR(255) NOT NULL,
    POST_CODE INT NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    HOUSE VARCHAR(255) NOT NULL,
    FLAT VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS CREDENTIALS
(
    LOGIN VARCHAR(255) PRIMARY KEY,
    PASS VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS SERVICES
(
    ID VARCHAR(255) NOT NULL,
    aTYPE VARCHAR(255) NOT NULL,
    PERIOD VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULL,
    PRIMARY KEY (aTYPE, PERIOD)
);

CREATE TABLE IF NOT EXISTS PLACES
(
    ID VARCHAR(255) PRIMARY KEY,
    CITY VARCHAR(255) NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULL,
    SERVICE_ID VARCHAR(255) NOT NULL,
    FOREIGN KEY (SERVICE_ID) REFERENCES services(id)
        ON DELETE RESTRICT
);
