CREATE DATABASE IF NOT EXISTS advertisepro;

USE advertisepro;

CREATE TABLE IF NOT EXISTS users
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(16) NOT NULL
);