CREATE DATABASE IF NOT EXISTS ADVERTISE_PRO;

USE ADVERTISE_PRO;

CREATE TABLE IF NOT EXISTS USERS
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(16) NOT NULL,
    LAST_NAME VARCHAR(16) NOT NULL,
    MIDDLE_NAME VARCHAR(16) NOT NULL,
    ROLE VARCHAR(32) NOT NULL,
);

CREATE TABLE IF NOT EXISTS CONTACTS
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL UNIQUE,
    CITY VARCHAR(32) NOT NULL,
    POST_CODE INT NOT NULL,
    STREET VARCHAR(32) NOT NULL,
    HOUSE INT NOT NULL,
    FLAT INT NOT NULL,
    PHONE VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(32) NOT NULL UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS CREDENTIALS
(
    LOGIN VARCHAR(32) PRIMARY KEY,
    PASSWORD VARCHAR(16) NOT NULL,
    USER_ID INT NOT NULL UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
